### ISSUE TITLE
Inception not working as feature extractor

### ISSUE THREAD

**Issue by omarcr** [fchollet/deep-learning-models#10]
when calling predict:

```
Traceback (most recent call last):
  File "/home/omar/Pycharm_ubuntu_v2/Spatial_v2_Aug-2016/features_from_keras_tool_RGB_final.py", line 72, in <module>
    model = InceptionV3(weights='imagenet', include_top=False)
  File "/home/omar/Pycharm_ubuntu_v2/Spatial_v2_Aug-2016/inception_v3.py", line 272, in InceptionV3
    model.load_weights(weights_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2446, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2518, in load_weights_from_hdf5_group
    ' elements.')
Exception: Layer #162 (named "batchnormalization_79" in the current model) was found to correspond to layer convolution2d_77 in the save file. However the new layer batchnormalization_79 expects 4 weights, but the saved weights have 2 elements.

Process finished with exit code 1
```

**Comment by movchan74** [comment]
These models requires the latest version of Keras (from the Github repo, not PyPI).

**Comment by omarcr** [comment]
I am using the latest version of Keras. Still not working after preprocessing as in the example given.

**Comment by movchan74** [comment]
Today I had the same problem. And it's gone after installing latest version of Keras from repo (like this sudo pip install  git+https://github.com/fchollet/keras.git). The version in master supports new type of weight's file which used in this model.

**Comment by omarcr** [comment]
Ok it is working now. The problem is that you have to first uninstall completely Keras and then install from git
