### ISSUE TITLE
inception model fails to load pretrained weights

### ISSUE THREAD

**Issue by xysmas** [fchollet/deep-learning-models#4]
I have used the resnet and vgg models successfully but cannot use the freshly released inception weights. 

Keras is on the latest master commit from github and i'm using anaconda python 3.5. 
-- Edit it was not on the 'latest' commit. It was on a commit from several days ago when I first cloned this repo; didn't realize it needed to be updated again.

Thoughts?

```
from inception_v3 import InceptionV3
from keras.preprocessing import image
from imagenet_utils import preprocess_input

model = InceptionV3(weights='imagenet', include_top=False)

Downloading data from https://github.com/fchollet/deep-learning-models/releases/download/v0.2/inception_v3_weights_th_dim_ordering_th_kernels_notop.h5
86679552/86916664 [============================>.] - ETA: 0s
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-5-881bb296c35e> in <module>()
      3 from imagenet_utils import preprocess_input
      4 
----> 5 model = InceptionV3(weights='imagenet', include_top=False)

/home/agonzales/git/image_classifier/src/inception_v3.py in InceptionV3(include_top, weights, input_tensor)
    279                                         cache_subdir='models',
    280                                         md5_hash='79aaa90ab4372b4593ba3df64e142f05')
--> 281             model.load_weights(weights_path)
    282             if K.backend() == 'tensorflow':
    283                 warnings.warn('You are using the TensorFlow backend, yet you '

/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/topology.py in load_weights(self, filepath)
   2444         if 'layer_names' not in f.attrs and 'model_weights' in f:
   2445             f = f['model_weights']
-> 2446         self.load_weights_from_hdf5_group(f)
   2447         if hasattr(f, 'close'):
   2448             f.close()

/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/topology.py in load_weights_from_hdf5_group(self, f)
   2516                                     ' weights, but the saved weights have ' +
   2517                                     str(len(weight_values)) +
-> 2518                                     ' elements.')
   2519                 weight_value_tuples += zip(symbolic_weights, weight_values)
   2520             K.batch_set_value(weight_value_tuples)

Exception: Layer #162 (named "batchnormalization_267" in the current model) was found to correspond to layer convolution2d_77 in the save file. However the new layer batchnormalization_267 expects 4 weights, but the saved weights have 2 elements.
```

**Comment by xysmas** [comment]
I just tested it with the Resnet50 model and am getting this error now:

```
from inception_v3 import InceptionV3
from resnet50 import ResNet50
from keras.preprocessing import image
from imagenet_utils import preprocess_input

model = ResNet50(weights='imagenet', include_top=False)
img_path = '/media/datadrive/tavr_images/test/155987_10180360_0_2016-04-13.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

model.predict(x)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:

ValueError: CorrMM images and kernel must have the same stack size


During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-88c8074af79e> in <module>()
----> 1 model.predict(x)

/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py in predict(self, x, batch_size, verbose)
   1178         f = self.predict_function
   1179         return self._predict_loop(f, ins,
-> 1180                                   batch_size=batch_size, verbose=verbose)
   1181 
   1182     def train_on_batch(self, x, y,

/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/training.py in _predict_loop(self, f, ins, batch_size, verbose)
    877                 ins_batch = slice_X(ins, batch_ids)
    878 
--> 879             batch_outs = f(ins_batch)
    880             if type(batch_outs) != list:
    881                 batch_outs = [batch_outs]

/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/backend/theano_backend.py in __call__(self, inputs)
    655     def __call__(self, inputs):
    656         assert type(inputs) in {list, tuple}
--> 657         return self.function(*inputs)
    658 
    659 

/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    869                     node=self.fn.nodes[self.fn.position_of_error],
    870                     thunk=thunk,
--> 871                     storage_map=getattr(self.fn, 'storage_map', None))
    872             else:
    873                 # old-style linkers raise their own exceptions

/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/theano/gof/link.py in raise_with_op(node, thunk, exc_info, storage_map)
    312         # extra long error message in that case.
    313         pass
--> 314     reraise(exc_type, exc_value, exc_trace)
    315 
    316 

/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/six.py in reraise(tp, value, tb)
    683             value = tp()
    684         if value.__traceback__ is not tb:
--> 685             raise value.with_traceback(tb)
    686         raise value
    687 

/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/theano/compile/function_module.py in __call__(self, *args, **kwargs)
    857         t0_fn = time.time()
    858         try:
--> 859             outputs = self.fn()
    860         except Exception:
    861             if hasattr(self.fn, 'position_of_error'):

ValueError: CorrMM images and kernel must have the same stack size

Apply node that caused the error: CorrMM{valid, (1, 1)}(Elemwise{Composite{(i0 * (Composite{Switch(i0, (((i1 - i2) * i3) + i4), (((i1 - i5) * i6) + i4))}(i1, i2, i3, i4, i5, i6, i7) + Abs(Composite{Switch(i0, (((i1 - i2) * i3) + i4), (((i1 - i5) * i6) + i4))}(i1, i2, i3, i4, i5, i6, i7))))}}.0, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 680
Inputs types: [TensorType(float32, 4D), TensorType(float32, 4D)]
Inputs shapes: [(1, 128, 28, 28), (512, 256, 1, 1)]
Inputs strides: [(401408, 3136, 112, 4), (1024, 4, -4, -4)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{add,no_inplace}(CorrMM{valid, (1, 1)}.0, Reshape{4}.0)]]

Backtrace when the node is created(use Theano flag traceback.limit=N to make it longer):
  File "<ipython-input-2-22f68392f03e>", line 6, in <module>
    model = ResNet50(weights='imagenet', include_top=False)
  File "/home/agonzales/git/image_classifier/src/resnet50.py", line 174, in ResNet50
    x = conv_block(x, 3, [128, 128, 512], stage=3, block='a')
  File "/home/agonzales/git/image_classifier/src/resnet50.py", line 99, in conv_block
    x = Convolution2D(nb_filter3, 1, 1, name=conv_name_base + '2c')(x)
  File "/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/topology.py", line 511, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/topology.py", line 569, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/layers/convolutional.py", line 353, in call
    filter_shape=self.W_shape)
  File "/home/agonzales/anaconda3/envs/keras_extract/lib/python3.5/site-packages/Keras-1.0.6-py3.5.egg/keras/backend/theano_backend.py", line 1056, in conv2d
    filter_shape=filter_shape)

HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
```

It works fine for VGG16.

**Comment by xysmas** [comment]
I didn't realize that keras wasn't on the absolute latest version from github, tagged 1.07. I recompiled from that version and everything is fine. I didn't even think about checking the tags on keras.
