### ISSUE TITLE
AttributeError: 'module' object has no attribute 'image_data_format'

### ISSUE THREAD

**Issue by MartinThoma** [fchollet/deep-learning-models#45]
```
>>> from resnet50 import ResNet50
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
>>> model = ResNet50(weights='imagenet')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "resnet50.py", line 192, in ResNet50
    data_format=K.image_data_format(),
AttributeError: 'module' object has no attribute 'image_data_format'
>>> from keras.preprocessing import image
>>> from imagenet_utils import preprocess_input, decode_predictions
>>> model = ResNet50(weights='imagenet')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "resnet50.py", line 192, in ResNet50
    data_format=K.image_data_format(),
AttributeError: 'module' object has no attribute 'image_data_format'
```

## My System

* Tensorflow 1.0.0
* Keras 1.2.2

**Comment by drumildeshpande** [comment]
Did you find a solution for this error ?

**Comment by rafalrusin** [comment]
Same error

**Comment by liutingxi** [comment]
Got the same error too.

**Comment by MartinThoma** [comment]
Pretty simple: Use https://github.com/fchollet/deep-learning-models/tree/8d8f54a9e1482c3642a55a694c2cde8f26562a06 

```
$ git checkout 8d8f54a9e1482c3642a55a694c2cde8f26562a06
```

The problems happen because the code was updated for Keras 2 and we have Keras 1.X
