### ISSUE TITLE
Error on trying to use inception_v3.py

### ISSUE THREAD

**Issue by Arsey** [fchollet/deep-learning-models#5]
I'm trying to use your inception_v3.py by following the example: 
```python
from inception_v3 import InceptionV3
from keras.preprocessing import image
from imagenet_utils import preprocess_input, decode_predictions

model = InceptionV3(weights='imagenet')

img_path = 'data/cat.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

preds = model.predict(x)
print('Predicted:', decode_predictions(preds))

```
And as a result I'm getting this error

```python
Using Theano backend.
Traceback (most recent call last):
  File "iv3.py", line 5, in <module>
    model = InceptionV3(weights='imagenet')
  File "inception_v3.py", line 281, in InceptionV3
    model.load_weights(weights_path)
  File "lib/python2.7/site-packages/keras/engine/topology.py", line 2446, in load_weights
    self.load_weights_from_hdf5_group(f)
  File "lib/python2.7/site-packages/keras/engine/topology.py", line 2518, in load_weights_from_hdf5_group
    ' elements.')
Exception: Layer #162 (named "batchnormalization_79" in the current model) was found to correspond to layer convolution2d_77 in the save file. However the new layer batchnormalization_79 expects 4 weights, but the saved weights have 2 elements.
```

**Comment by movchan74** [comment]
#10

**Comment by jakebian** [comment]
Same here @fchollet, any ideas?
