### ISSUE TITLE
VGG19 fails to run (on Keras v2.0.9)

### ISSUE THREAD

**Issue by konpatp** [fchollet/deep-learning-models#77]
Here is the error (vgg19.py) : 
```
Traceback (most recent call last):
  File "vgg19.py", line 195, in <module>
    model = VGG19(include_top=True, weights='imagenet')
  File "vgg19.py", line 100, in VGG19
    include_top=include_top)
TypeError: _obtain_input_shape() got an unexpected keyword argument 'include_top'
```

**Comment by zouqian2468** [comment]
you can change 'include_top=include_top" to "require_flatten=include_top".
